configfile: "config/config.yaml"


include: "rules/common.smk"
include: "rules/reference.smk"
include: "rules/trim.smk"
include: "rules/align.smk"
include: "rules/imputation.smk"


onstart:
    print(f"--- {len(SAMPLES)} samples, {len(CHROMS)} chromosomes ---")


onsuccess:
    print("--- Workflow finished ---")


onerror:
    print("--- Workflow failed ---")


rule all:
    default_target: True
    input:
        expand("results/imputed/{chrom}.bcf", chrom=CHROMS),
        expand("results/imputed/{chrom}.bcf.csi", chrom=CHROMS),
