configfile: "config/config.yaml"


include: "rules/common.smk"
include: "rules/reference.smk"
include: "rules/qc_trim.smk"
include: "rules/align.smk"
include: "rules/imputation.smk"
include: "rules/multiqc.smk"


onstart:
    print(f"--- {len(SAMPLES)} samples, {len(CHROMS)} chromosomes ---")


onsuccess:
    print("--- Workflow finished ---")


onerror:
    print("--- Workflow failed ---")


rule all:
    default_target: True
    input:
        expand("results/imputed/{chrom}.vcf.gz", chrom=CHROMS),
        expand("results/imputed/{chrom}.vcf.gz.tbi", chrom=CHROMS),
        "results/multiqc/multiqc_report.html",
