executor: "slurm"
jobs: 600

printshellcmds: true
software-deployment-method: conda
max-jobs-per-second: 10
latency-wait: 30
max-status-checks-per-second: 5
scheduler: greedy
local-cores: 1

default-resources:
  slurm_partition: "normal,fat"
  slurm_account: "rlchen"
  mem_mb: 2000
  nodes: 1
  cpus_per_task: 1
  runtime: 240
