sample_sheet: "config/samples.tsv"

reference:
  fasta: "resources/reference/IRGSP-1.0_genome.fasta"

panel:
  full_template: "resources/ref_panel/311/{chrom}.vcf.gz"
  sites_tsv_template: "resources/ref_panel/311/{chrom}.tsv.gz"

chromosomes:
  - "chr01"
  - "chr02"
  - "chr03"
  - "chr04"
  - "chr05"
  - "chr06"
  - "chr07"
  - "chr08"
  - "chr09"
  - "chr10"
  - "chr11"
  - "chr12"

genetic_map:
  template: "resources/map/{chrom}.map"

merge_gl:
  batch_size: 200

glimpse_chunk:
  window_size: 2000000
  buffer_size: 200000
  extra: ""

fastp:
  extra: ""
