sample_sheet: "config/samples.tsv"

reference:
  fasta: "resources/reference/IRGSP-1.0_genome.fasta"

panel:
  full_template: "resources/reference/hybrid_reference_{chrom}_addACAN.bcf"
  sites_template: "resources/reference/hybrid_reference_{chrom}.sites.vcf.gz"

chromosomes:
  - "chr01"
  - "chr02"
  - "chr03"
  - "chr04"
  - "chr05"
  - "chr06"
  - "chr07"
  - "chr08"
  - "chr09"
  - "chr10"
  - "chr11"
  - "chr12"

genetic_map:
  template: "resources/map/rice_genetic_{chrom}.map"

glimpse2_chunk:
  window_mb: 4.0
  buffer_mb: 0.5
  extra: ""

fastp:
  extra: ""
