sample_sheet: "config/samples.tsv"

reference:
  fasta: "resources/reference/chr22.fa"

panel:
  full_template: "resources/panel/1000GP.{chrom}.noNA12878.bcf"
  sites_template: "resources/panel/1000GP.{chrom}.noNA12878.sites.vcf.gz"

chromosomes:
  - "chr22"

genetic_map:
  template: "resources/maps/{chrom}.gmap"

glimpse2_chunk:
  window_mb: 4.0
  buffer_mb: 0.5
  extra: ""

fastp:
  extra: ""
